apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgadmin
    spec:
      containers:
        - image: dpage/pgadmin4
          name: pgadmin4
          resources: {}
          env:
            - name: PGADMIN_DEFAULT_EMAIL # todo! secret
              value: pgadmin4@pgadmin.org
            - name: PGADMIN_DEFAULT_PASSWORD # todo! secret
              value: admin
status: {}
