use warp::Rejection;

#[macro_use]
extern crate diesel;

pub mod auth;
pub mod dto;
pub mod error;
pub mod models;
pub mod repository;
pub mod seed;

// Contents auto-generated by Diesel upon Migrations
pub mod schema;

pub type WebResult<T> = std::result::Result<T, Rejection>;
pub type Result<T> = std::result::Result<T, error::Error>;
