apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-rs
  name: api-rs-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api-rs
  type: ClusterIP
status:
  loadBalancer: {}
